// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdEEgMgL09fv6WNZ_gifc3wG3aqZu7CH4',
    appId: '1:905818683767:web:ab3e3a921a658138ea0972',
    messagingSenderId: '905818683767',
    projectId: 'fir-practce-set-app',
    authDomain: 'fir-practce-set-app.firebaseapp.com',
    storageBucket: 'fir-practce-set-app.appspot.com',
    measurementId: 'G-G8108W50ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaW9fJoTmIaxBIOhacXK4rVDjBqDIHG8A',
    appId: '1:905818683767:android:d0f5681840c5c844ea0972',
    messagingSenderId: '905818683767',
    projectId: 'fir-practce-set-app',
    storageBucket: 'fir-practce-set-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdT7f7vkqRjScgbSIGQUREiy04Ff4Kkb4',
    appId: '1:905818683767:ios:a571f0d2b5293014ea0972',
    messagingSenderId: '905818683767',
    projectId: 'fir-practce-set-app',
    storageBucket: 'fir-practce-set-app.appspot.com',
    iosClientId: '905818683767-i6p5bc8f69pm01ma4lq51dca8bp69ul9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractceSetApp',
  );
}
